import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://ydzsjqilnkcvbcnkgcrh.supabase.co'
const supabaseKey = 'sb_publishable_2zrRyGhtStU3INgrDP9BEA_3URWnRBl'
const supabase = createClient(supabaseUrl, supabaseKey)

const vocabulary = [
  // Lesson 1 - Pinyin Basics
  { hanzi: '妈', pinyin: 'mā', indonesian: 'ibu', english: 'mother (tone 1 example)' },
  { hanzi: '麻', pinyin: 'má', indonesian: 'rami', english: 'hemp (tone 2 example)' },
  { hanzi: '马', pinyin: 'mǎ', indonesian: 'kuda', english: 'horse (tone 3 example)' },
  { hanzi: '骂', pinyin: 'mà', indonesian: 'memarahi', english: 'scold (tone 4 example)' },

  // Lesson 2 - Greetings
  { hanzi: '我', pinyin: 'wǒ', indonesian: 'saya', english: 'I; me' },
  { hanzi: '你', pinyin: 'nǐ', indonesian: 'kamu', english: 'you' },
  { hanzi: '您', pinyin: 'nín', indonesian: 'anda (sopan)', english: 'you (polite)' },
  { hanzi: '他', pinyin: 'tā', indonesian: 'dia (laki-laki)', english: 'he; him' },
  { hanzi: '她', pinyin: 'tā', indonesian: 'dia (perempuan)', english: 'she; her' },
  { hanzi: '它', pinyin: 'tā', indonesian: 'dia (binatang/benda)', english: 'it' },
  { hanzi: '我们', pinyin: 'wǒmen', indonesian: 'kami; kita', english: 'we; us' },
  { hanzi: '你们', pinyin: 'nǐmen', indonesian: 'kalian', english: 'you (plural)' },
  { hanzi: '他们', pinyin: 'tāmen', indonesian: 'mereka', english: 'they (mixed/male)' },
  { hanzi: '她们', pinyin: 'tāmen', indonesian: 'mereka (perempuan)', english: 'they (female)' },
  { hanzi: '好', pinyin: 'hǎo', indonesian: 'baik', english: 'good' },
  { hanzi: '你好', pinyin: 'nǐ hǎo', indonesian: 'halo', english: 'hello' },
  { hanzi: '您好', pinyin: 'nín hǎo', indonesian: 'halo (sopan)', english: 'hello (polite)' },
  { hanzi: '老师', pinyin: 'lǎoshī', indonesian: 'guru', english: 'teacher' },
  { hanzi: '大家', pinyin: 'dàjiā', indonesian: 'semuanya', english: 'everyone' },
  { hanzi: '学生', pinyin: 'xuéshēng', indonesian: 'murid', english: 'student' },
  { hanzi: '们', pinyin: 'men', indonesian: 'akhiran jamak', english: 'plural suffix' },
  { hanzi: '谢谢', pinyin: 'xièxie', indonesian: 'terima kasih', english: 'thank you' },
  { hanzi: '不客气', pinyin: 'bú kèqì', indonesian: 'sama-sama', english: "you're welcome" },
  { hanzi: '对不起', pinyin: 'duìbùqǐ', indonesian: 'maaf', english: 'sorry' },
  { hanzi: '没关系', pinyin: 'méi guānxi', indonesian: 'tidak apa-apa', english: "it's okay" },
  { hanzi: '再见', pinyin: 'zàijiàn', indonesian: 'sampai jumpa', english: 'goodbye' },
  { hanzi: '吗', pinyin: 'ma', indonesian: 'partikel tanya', english: 'question particle' },
  { hanzi: '你好吗', pinyin: 'nǐ hǎo ma', indonesian: 'apa kabar?', english: 'how are you?' },
  { hanzi: '我很好', pinyin: 'wǒ hěn hǎo', indonesian: 'saya sangat baik', english: "I'm very well" },
  { hanzi: '不错', pinyin: 'bú cuò', indonesian: 'tidak buruk', english: 'not bad' },
  { hanzi: '还可以', pinyin: 'hái kěyǐ', indonesian: 'lumayan', english: "it's okay" },
  { hanzi: '不太好', pinyin: 'bú tài hǎo', indonesian: 'kurang baik', english: 'not so good' },
  { hanzi: '呢', pinyin: 'ne', indonesian: 'partikel akhir kalimat', english: 'sentence-final particle' },
  { hanzi: '也', pinyin: 'yě', indonesian: 'juga', english: 'also' },
  { hanzi: '早上', pinyin: 'zǎoshang', indonesian: 'pagi', english: 'morning' },
  { hanzi: '早上好', pinyin: 'zǎoshang hǎo', indonesian: 'selamat pagi', english: 'good morning' },
  { hanzi: '中午好', pinyin: 'zhōngwǔ hǎo', indonesian: 'selamat siang', english: 'good noon' },
  { hanzi: '下午好', pinyin: 'xiàwǔ hǎo', indonesian: 'selamat sore', english: 'good afternoon' },
  { hanzi: '晚上好', pinyin: 'wǎnshang hǎo', indonesian: 'selamat malam', english: 'good evening' },

  // Lesson 4 - Nationality
  { hanzi: '哪', pinyin: 'nǎ', indonesian: 'mana', english: 'which; where' },
  { hanzi: '国', pinyin: 'guó', indonesian: 'negara', english: 'country' },
  { hanzi: '国家', pinyin: 'guójiā', indonesian: 'negara', english: 'country (full)' },
  { hanzi: '人', pinyin: 'rén', indonesian: 'orang', english: 'person; people' },
  { hanzi: '中国', pinyin: 'Zhōngguó', indonesian: 'Tiongkok', english: 'China' },
  { hanzi: '美国', pinyin: 'Měiguó', indonesian: 'Amerika', english: 'USA' },
  { hanzi: '法国', pinyin: 'Fǎguó', indonesian: 'Perancis', english: 'France' },
  { hanzi: '日本', pinyin: 'Rìběn', indonesian: 'Jepang', english: 'Japan' },
  { hanzi: '印度尼西亚', pinyin: 'Yìndùníxīyà', indonesian: 'Indonesia', english: 'Indonesia' },
  { hanzi: '印尼', pinyin: 'Yìnní', indonesian: 'Indonesia (singkat)', english: 'Indonesia (short)' },
  { hanzi: '中文', pinyin: 'Zhōngwén', indonesian: 'bahasa Mandarin', english: 'Chinese language' },
  { hanzi: '这', pinyin: 'zhè', indonesian: 'ini', english: 'this' },
  { hanzi: '谁', pinyin: 'shéi', indonesian: 'siapa', english: 'who' },
  { hanzi: '女', pinyin: 'nǚ', indonesian: 'perempuan', english: 'girl; woman' },
  { hanzi: '男', pinyin: 'nán', indonesian: 'laki-laki', english: 'boy; man' },
  { hanzi: '朋友', pinyin: 'péngyou', indonesian: 'teman', english: 'friend' },
  { hanzi: '泰国', pinyin: 'Tàiguó', indonesian: 'Thailand', english: 'Thailand' },
  { hanzi: '是', pinyin: 'shì', indonesian: 'adalah', english: 'to be' },
  { hanzi: '的', pinyin: 'de', indonesian: 'partikel kepemilikan', english: 'possessive particle' },

  // Lesson 5 - Occupation
  { hanzi: '医生', pinyin: 'yīshēng', indonesian: 'dokter', english: 'doctor' },
  { hanzi: '做', pinyin: 'zuò', indonesian: 'melakukan', english: 'do; make' },
  { hanzi: '什么', pinyin: 'shénme', indonesian: 'apa', english: 'what' },
  { hanzi: '工作', pinyin: 'gōngzuò', indonesian: 'pekerjaan', english: 'job; work' },
  { hanzi: '喂', pinyin: 'wèi', indonesian: 'halo (di telepon)', english: 'hello (on phone)' },
  { hanzi: '还', pinyin: 'hái', indonesian: 'masih', english: 'still' },
  { hanzi: '忙', pinyin: 'máng', indonesian: 'sibuk', english: 'busy' },
  { hanzi: '对', pinyin: 'duì', indonesian: 'benar', english: 'right; correct' },
  { hanzi: '太', pinyin: 'tài', indonesian: 'terlalu', english: 'too; excessively' },
  { hanzi: '想', pinyin: 'xiǎng', indonesian: 'ingin; rindu', english: 'want; miss' },

  // Lesson 6.1 - Numbers
  { hanzi: '零', pinyin: 'líng', indonesian: 'nol (0)', english: 'zero (0)' },
  { hanzi: '一', pinyin: 'yī', indonesian: 'satu (1)', english: 'one (1)' },
  { hanzi: '二', pinyin: 'èr', indonesian: 'dua (2)', english: 'two (2)' },
  { hanzi: '三', pinyin: 'sān', indonesian: 'tiga (3)', english: 'three (3)' },
  { hanzi: '四', pinyin: 'sì', indonesian: 'empat (4)', english: 'four (4)' },
  { hanzi: '五', pinyin: 'wǔ', indonesian: 'lima (5)', english: 'five (5)' },
  { hanzi: '六', pinyin: 'liù', indonesian: 'enam (6)', english: 'six (6)' },
  { hanzi: '七', pinyin: 'qī', indonesian: 'tujuh (7)', english: 'seven (7)' },
  { hanzi: '八', pinyin: 'bā', indonesian: 'delapan (8)', english: 'eight (8)' },
  { hanzi: '九', pinyin: 'jiǔ', indonesian: 'sembilan (9)', english: 'nine (9)' },
  { hanzi: '十', pinyin: 'shí', indonesian: 'sepuluh (10)', english: 'ten (10)' },
  { hanzi: '百', pinyin: 'bǎi', indonesian: 'ratusan', english: 'hundred' },
  { hanzi: '千', pinyin: 'qiān', indonesian: 'ribuan', english: 'thousand' },
  { hanzi: '万', pinyin: 'wàn', indonesian: 'sepuluh ribu', english: 'ten thousand' },
  { hanzi: '两', pinyin: 'liǎng', indonesian: 'dua (untuk jumlah)', english: 'two (for quantity)' },

  // Lesson 6.2 - Family & Age
  { hanzi: '爸爸', pinyin: 'bàba', indonesian: 'ayah; papa', english: 'father; dad' },
  { hanzi: '妈妈', pinyin: 'māma', indonesian: 'ibu; mama', english: 'mother; mom' },
  { hanzi: '哥哥', pinyin: 'gēge', indonesian: 'kakak laki-laki', english: 'older brother' },
  { hanzi: '姐姐', pinyin: 'jiějie', indonesian: 'kakak perempuan', english: 'older sister' },
  { hanzi: '弟弟', pinyin: 'dìdi', indonesian: 'adik laki-laki', english: 'younger brother' },
  { hanzi: '妹妹', pinyin: 'mèimei', indonesian: 'adik perempuan', english: 'younger sister' },
  { hanzi: '家', pinyin: 'jiā', indonesian: 'rumah; keluarga', english: 'house; home; family' },
  { hanzi: '有', pinyin: 'yǒu', indonesian: 'ada; punya', english: 'have; has' },
  { hanzi: '没有', pinyin: 'méiyǒu', indonesian: 'tidak ada; tidak punya', english: 'not have' },
  { hanzi: '几', pinyin: 'jǐ', indonesian: 'berapa (jumlah kecil)', english: 'how many (small)' },
  { hanzi: '口', pinyin: 'kǒu', indonesian: 'MW keluarga; mulut', english: 'MW for family; mouth' },
  { hanzi: '和', pinyin: 'hé', indonesian: 'dan; dengan', english: 'and; with' },
  { hanzi: '多少', pinyin: 'duōshǎo', indonesian: 'berapa', english: 'how many; how much' },
  { hanzi: '个', pinyin: 'gè', indonesian: 'kata bilangan umum', english: 'general measure word' },
  { hanzi: '儿子', pinyin: 'érzi', indonesian: 'anak laki-laki', english: 'son' },
  { hanzi: '孩子', pinyin: 'háizi', indonesian: 'anak', english: 'child; children' },
  { hanzi: '女儿', pinyin: "nǚ'ér", indonesian: 'anak perempuan', english: 'daughter' },
  { hanzi: '今年', pinyin: 'jīnnián', indonesian: 'tahun ini', english: 'this year' },
  { hanzi: '岁', pinyin: 'suì', indonesian: 'tahun (umur)', english: 'years (of age)' },
  { hanzi: '多', pinyin: 'duō', indonesian: 'banyak', english: 'much; many' },
  { hanzi: '大', pinyin: 'dà', indonesian: 'besar', english: 'big; large' },
  { hanzi: '多大', pinyin: 'duō dà', indonesian: 'berapa umur/besar', english: 'how old; how big' },

  // Lesson 7 - Dates, Ability & Likings
  { hanzi: '今天', pinyin: 'jīntiān', indonesian: 'hari ini', english: 'today' },
  { hanzi: '年', pinyin: 'nián', indonesian: 'tahun', english: 'year' },
  { hanzi: '月', pinyin: 'yuè', indonesian: 'bulan', english: 'month' },
  { hanzi: '号', pinyin: 'hào', indonesian: 'tanggal', english: 'date; number' },
  { hanzi: '日', pinyin: 'rì', indonesian: 'tanggal; matahari', english: 'sun; date' },
  { hanzi: '星期', pinyin: 'xīngqī', indonesian: 'minggu', english: 'week' },
  { hanzi: '休息', pinyin: 'xiūxi', indonesian: 'istirahat', english: 'rest' },
  { hanzi: '会', pinyin: 'huì', indonesian: 'bisa (skill)', english: 'can; be able to' },
  { hanzi: '做饭', pinyin: 'zuòfàn', indonesian: 'memasak', english: 'cook' },
  { hanzi: '米饭', pinyin: 'mǐfàn', indonesian: 'nasi', english: 'rice' },
  { hanzi: '面条儿', pinyin: 'miàntiáor', indonesian: 'mie', english: 'noodles' },
  { hanzi: '饺子', pinyin: 'jiǎozi', indonesian: 'pangsit', english: 'dumplings' },
  { hanzi: '一些', pinyin: 'yìxiē', indonesian: 'beberapa', english: 'some' },
  { hanzi: '菜', pinyin: 'cài', indonesian: 'sayur; masakan', english: 'vegetable; dish' },
  { hanzi: '上班', pinyin: 'shàngbān', indonesian: 'masuk kerja', english: 'go to work' },
  { hanzi: '下班', pinyin: 'xiàbān', indonesian: 'pulang kerja', english: 'get off work' },
  { hanzi: '新', pinyin: 'xīn', indonesian: 'baru', english: 'new' },
  { hanzi: '电脑', pinyin: 'diànnǎo', indonesian: 'komputer', english: 'computer' },
  { hanzi: '真', pinyin: 'zhēn', indonesian: 'sangat; sungguh', english: 'really; truly' },
  { hanzi: '好看', pinyin: 'hǎokàn', indonesian: 'bagus; cakep', english: 'good-looking; nice' },
  { hanzi: '喜欢', pinyin: 'xǐhuan', indonesian: 'suka', english: 'like' },

  // Lesson 8 - Phone Number
  { hanzi: '手机', pinyin: 'shǒujī', indonesian: 'handphone', english: 'mobile phone' },
  { hanzi: '电话', pinyin: 'diànhuà', indonesian: 'telefon', english: 'telephone' },
  { hanzi: '号码', pinyin: 'hàomǎ', indonesian: 'nomor', english: 'number' },
  { hanzi: '明天', pinyin: 'míngtiān', indonesian: 'besok', english: 'tomorrow' },
  { hanzi: '去', pinyin: 'qù', indonesian: 'pergi', english: 'go to' },
  { hanzi: '哪儿', pinyin: 'nǎr', indonesian: 'mana', english: 'where' },
  { hanzi: '超市', pinyin: 'chāoshì', indonesian: 'supermarket', english: 'supermarket' },
  { hanzi: '买', pinyin: 'mǎi', indonesian: 'membeli', english: 'buy' },
  { hanzi: '东西', pinyin: 'dōngxi', indonesian: 'barang', english: 'thing' },
  { hanzi: '些', pinyin: 'xiē', indonesian: 'beberapa', english: 'some; a few' },
  { hanzi: '牛奶', pinyin: 'niúnǎi', indonesian: 'susu sapi', english: "(cow's) milk" },
  { hanzi: '吃', pinyin: 'chī', indonesian: 'makan', english: 'eat' },
  { hanzi: '晚饭', pinyin: 'wǎnfàn', indonesian: 'makan malam', english: 'dinner' },
  { hanzi: '那边', pinyin: 'nàbiān', indonesian: 'di sisi itu; sana', english: 'there' },
  { hanzi: '包子', pinyin: 'bāozi', indonesian: 'bakpao', english: 'steamed bun' },
  { hanzi: '非常', pinyin: 'fēicháng', indonesian: 'sangat', english: 'very; extremely' },
  { hanzi: '好吃', pinyin: 'hǎochī', indonesian: 'enak', english: 'delicious' },
  { hanzi: '怎么', pinyin: 'zěnme', indonesian: 'bagaimana cara', english: 'how' },
  { hanzi: '坐', pinyin: 'zuò', indonesian: 'duduk; naik', english: 'sit; take (transport)' },
  { hanzi: '出租车', pinyin: 'chūzūchē', indonesian: 'taksi', english: 'taxi' },

  // Lesson 9 - Time
  { hanzi: '现在', pinyin: 'xiànzài', indonesian: 'sekarang', english: 'now' },
  { hanzi: '点', pinyin: 'diǎn', indonesian: 'jam', english: "o'clock" },
  { hanzi: '分', pinyin: 'fēn', indonesian: 'menit', english: 'minute' },
  { hanzi: '课', pinyin: 'kè', indonesian: 'kelas; pelajaran', english: 'class; lesson' },
  { hanzi: '见', pinyin: 'jiàn', indonesian: 'bertemu', english: 'meet' },
  { hanzi: '吧', pinyin: 'ba', indonesian: 'partikel saran', english: 'suggestion particle' },
  { hanzi: '上午', pinyin: 'shàngwǔ', indonesian: 'pagi (09-12)', english: 'morning' },
  { hanzi: '中午', pinyin: 'zhōngwǔ', indonesian: 'siang (12-13)', english: 'noon' },
  { hanzi: '下午', pinyin: 'xiàwǔ', indonesian: 'siang-sore (13-18)', english: 'afternoon' },
  { hanzi: '傍晚', pinyin: 'bàngwǎn', indonesian: 'sore (17-19)', english: 'dusk; early evening' },
  { hanzi: '晚上', pinyin: 'wǎnshang', indonesian: 'malam (18-24)', english: 'evening; night' },
  { hanzi: '夜里', pinyin: 'yèlǐ', indonesian: 'malam (>=22)', english: 'late night' },
  { hanzi: '凌晨', pinyin: 'língchén', indonesian: 'subuh (24-05)', english: 'early dawn' },
  { hanzi: '电影院', pinyin: 'diànyǐngyuàn', indonesian: 'bioskop', english: 'cinema' },
  { hanzi: '看', pinyin: 'kàn', indonesian: 'nonton; lihat; baca', english: 'watch; see; read' },
  { hanzi: '电影', pinyin: 'diànyǐng', indonesian: 'film', english: 'movie' },
  { hanzi: '事', pinyin: 'shì', indonesian: 'sesuatu; masalah', english: 'thing; affair' },
  { hanzi: '上课', pinyin: 'shàngkè', indonesian: 'masuk kelas', english: 'attend a class' },
  { hanzi: '下课', pinyin: 'xiàkè', indonesian: 'selesai kelas', english: 'dismiss a class' },
  { hanzi: '半', pinyin: 'bàn', indonesian: 'setengah (30 menit)', english: 'half' },
  { hanzi: '刻', pinyin: 'kè', indonesian: 'seperempat jam (15 menit)', english: 'quarter hour' },
  { hanzi: '里', pinyin: 'lǐ', indonesian: 'dalam', english: 'inner; inside' },
  { hanzi: '医院', pinyin: 'yīyuàn', indonesian: 'rumah sakit', english: 'hospital' },
  { hanzi: '店', pinyin: 'diàn', indonesian: 'toko', english: 'shop; store' },
  { hanzi: '分钟', pinyin: 'fēnzhōng', indonesian: 'menit (durasi)', english: 'minute (duration)' },
  { hanzi: '后', pinyin: 'hòu', indonesian: 'setelah; nanti', english: 'after; later' },

  // Lesson 10 - Location
  { hanzi: '房间', pinyin: 'fángjiān', indonesian: 'kamar', english: 'room' },
  { hanzi: '外', pinyin: 'wài', indonesian: 'luar', english: 'outside' },
  { hanzi: '只', pinyin: 'zhī', indonesian: 'kata satuan untuk binatang', english: 'MW for animals' },
  { hanzi: '小', pinyin: 'xiǎo', indonesian: 'kecil', english: 'small; little' },
  { hanzi: '猫', pinyin: 'māo', indonesian: 'kucing', english: 'cat' },
  { hanzi: '没', pinyin: 'méi', indonesian: 'tidak; belum', english: 'no; not; not yet' },
  { hanzi: '看见', pinyin: 'kànjiàn', indonesian: 'melihat', english: 'see; catch sight of' },
  { hanzi: '桌子', pinyin: 'zhuōzi', indonesian: 'meja', english: 'table; desk' },
  { hanzi: '下', pinyin: 'xià', indonesian: 'bawah', english: 'below; under' },
  { hanzi: '漂亮', pinyin: 'piàoliang', indonesian: 'cantik', english: 'pretty; beautiful' },
  { hanzi: '左边', pinyin: 'zuǒbiān', indonesian: 'sebelah kiri', english: 'left side' },
  { hanzi: '右边', pinyin: 'yòubiān', indonesian: 'sebelah kanan', english: 'right side' },
  { hanzi: '后边', pinyin: 'hòubiān', indonesian: 'belakang', english: 'back side' },
  { hanzi: '面', pinyin: 'miàn', indonesian: 'sisi', english: 'surface; face; side' },
  { hanzi: '下面', pinyin: 'xiàmiàn', indonesian: 'bawah', english: 'below; under' },
  { hanzi: '上面', pinyin: 'shàngmiàn', indonesian: 'atas', english: 'above; top' },
  { hanzi: '里面', pinyin: 'lǐmiàn', indonesian: 'dalam', english: 'inside' },
  { hanzi: '外面', pinyin: 'wàimiàn', indonesian: 'luar', english: 'outside' },
  { hanzi: '在', pinyin: 'zài', indonesian: 'di', english: 'at; in; on' },
  { hanzi: '学校', pinyin: 'xuéxiào', indonesian: 'sekolah', english: 'school' },
  { hanzi: '书店', pinyin: 'shūdiàn', indonesian: 'toko buku', english: 'bookstore' },
  { hanzi: '能', pinyin: 'néng', indonesian: 'bisa; dapat', english: 'can; be able to' },
  { hanzi: '到', pinyin: 'dào', indonesian: 'sampai', english: 'arrive; reach' },
  { hanzi: '午饭', pinyin: 'wǔfàn', indonesian: 'makan siang', english: 'lunch' },
  { hanzi: '饭', pinyin: 'fàn', indonesian: 'makanan', english: 'meal' },
  { hanzi: '病人', pinyin: 'bìngrén', indonesian: 'orang sakit; pasien', english: 'patient' },

  // Lesson 11 - Sequence of Time & Location
  { hanzi: '边', pinyin: 'biān', indonesian: 'sebelah', english: 'side; edge; direction' },
  { hanzi: '前边', pinyin: 'qiánbian', indonesian: 'sebelah depan', english: 'front side' },
  { hanzi: '外边', pinyin: 'wàibian', indonesian: 'luar', english: 'outside' },
  { hanzi: '那个', pinyin: 'nà ge', indonesian: 'yang itu', english: 'that one' },
  { hanzi: '椅子', pinyin: 'yǐzi', indonesian: 'kursi', english: 'chair' },
  { hanzi: '上', pinyin: 'shàng', indonesian: 'atas', english: 'above; on' },
  { hanzi: '本', pinyin: 'běn', indonesian: 'kata bilangan untuk buku', english: 'MW for books' },
  { hanzi: '书', pinyin: 'shū', indonesian: 'buku', english: 'book' },
  { hanzi: '第', pinyin: 'dì', indonesian: 'ke-___', english: 'ordinal number marker' },
  { hanzi: '学习', pinyin: 'xuéxí', indonesian: 'belajar', english: 'study' },
  { hanzi: '白天', pinyin: 'báitiān', indonesian: 'siang hari', english: 'day time' },
  { hanzi: '读书', pinyin: 'dú shū', indonesian: 'membaca buku', english: 'read a book' },
  { hanzi: '唱', pinyin: 'chàng', indonesian: 'menyanyi', english: 'sing' },
  { hanzi: '歌', pinyin: 'gē', indonesian: 'lagu', english: 'song' },
  { hanzi: '好听', pinyin: 'hǎotīng', indonesian: 'enak didengar', english: 'pleasant to hear' },
  { hanzi: '电视', pinyin: 'diànshì', indonesian: 'televisi', english: 'TV' },
  { hanzi: '狗', pinyin: 'gǒu', indonesian: 'anjing', english: 'dog' },
  { hanzi: '玩', pinyin: 'wán', indonesian: 'bermain', english: 'play' },
]

async function seed() {
  console.log(`Inserting ${vocabulary.length} words...`)

  const { error } = await supabase
    .from('characters')
    .upsert(vocabulary, { onConflict: 'hanzi' })

  if (error) {
    console.error('Error:', error.message)
  } else {
    console.log('Done! All words inserted successfully.')
  }
}

seed()
