import { createClient } from '@supabase/supabase-js'

// Pass credentials as env vars so this script can target any Supabase project:
//   SUPABASE_URL=https://xxxx.supabase.co SUPABASE_KEY=sb_xxx node scripts/seed.mjs
// Falls back to the production project's credentials if not set.
const supabaseUrl = process.env.SUPABASE_URL || 'https://ydzsjqilnkcvbcnkgcrh.supabase.co'
const supabaseKey = process.env.SUPABASE_KEY || 'sb_publishable_2zrRyGhtStU3INgrDP9BEA_3URWnRBl'
const supabase = createClient(supabaseUrl, supabaseKey)

const lessonNames = [
  'Lesson 1 – Pinyin',
  'Lesson 2 – Greetings',
  'Lesson 4 – Nationality',
  'Lesson 5 – Occupation',
  'Lesson 6.1 – Numbers',
  'Lesson 6.2 – Family & Age',
  'Lesson 7 – Dates & Likings',
  'Lesson 8 – Phone Number',
  'Lesson 9 – Time',
  'Lesson 10 – Location',
  'Lesson 11 – Review',
  'Lesson 12 – Price',
  'Lesson 13 – 在 as V-ing',
]

const vocabulary = [
  // ── Lesson 1 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 1 – Pinyin', hanzi: '你好', pinyin: 'nǐ hǎo', english: 'hello', indonesian: 'halo' },

  // ── Lesson 2 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 2 – Greetings', hanzi: '我', pinyin: 'wǒ', english: 'I; me', indonesian: 'saya' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '你', pinyin: 'nǐ', english: 'you', indonesian: 'kamu' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '您', pinyin: 'nín', english: 'you (polite)', indonesian: 'anda' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '他', pinyin: 'tā', english: 'he; him', indonesian: 'dia (laki-laki)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '她', pinyin: 'tā', english: 'she; her', indonesian: 'dia (perempuan)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '它', pinyin: 'tā', english: 'it (animal/thing)', indonesian: 'dia (binatang)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '我们', pinyin: 'wǒmen', english: 'we; us', indonesian: 'kami; kita' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '你们', pinyin: 'nǐmen', english: 'you (plural)', indonesian: 'kalian' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '您们', pinyin: 'nínmen', english: 'you (plural, polite)', indonesian: 'kalian (sopan)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '他们', pinyin: 'tāmen', english: 'they (male/mixed)', indonesian: 'mereka' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '她们', pinyin: 'tāmen', english: 'they (all female)', indonesian: 'mereka (perempuan)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '它们', pinyin: 'tāmen', english: 'they (animals/things)', indonesian: 'mereka (binatang)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '好', pinyin: 'hǎo', english: 'good', indonesian: 'baik' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '你好', pinyin: 'nǐ hǎo', english: 'hello', indonesian: 'halo' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '您好', pinyin: 'nín hǎo', english: 'hello (polite)', indonesian: 'halo (sopan)' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '老师', pinyin: 'lǎoshī', english: 'teacher', indonesian: 'guru' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '大家', pinyin: 'dàjiā', english: 'everyone', indonesian: 'semuanya' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '学生', pinyin: 'xuéshēng', english: 'student', indonesian: 'murid' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '们', pinyin: 'men', english: 'plural marker', indonesian: 'penanda jamak' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '谢谢', pinyin: 'xièxie', english: 'thank you', indonesian: 'terima kasih' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '不客气', pinyin: 'bú kèqì', english: "you're welcome", indonesian: 'sama-sama' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '对不起', pinyin: 'duìbuqǐ', english: 'sorry', indonesian: 'maaf' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '没关系', pinyin: 'méi guānxi', english: "it's okay", indonesian: 'tidak apa-apa' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '再见', pinyin: 'zàijiàn', english: 'goodbye', indonesian: 'sampai jumpa' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '吗', pinyin: 'ma', english: 'question particle', indonesian: 'partikel tanya' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '你好吗', pinyin: 'nǐ hǎo ma', english: 'how are you?', indonesian: 'apa kabar?' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '我很好', pinyin: 'wǒ hěn hǎo', english: "I'm very well", indonesian: 'saya sangat baik' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '我不错', pinyin: 'wǒ bú cuò', english: "I'm not bad", indonesian: 'saya tidak buruk' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '还可以', pinyin: 'hái kěyǐ', english: 'so-so; it\'s okay', indonesian: 'masih bisa; lumayan' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '不太好', pinyin: 'bú tài hǎo', english: 'not so good', indonesian: 'tidak begitu baik' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '呢', pinyin: 'ne', english: 'sentence-final particle', indonesian: 'partikel akhir kalimat' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '你呢', pinyin: 'nǐ ne', english: 'and you?', indonesian: 'dan kamu?' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '也', pinyin: 'yě', english: 'also; too', indonesian: 'juga' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '我也很好', pinyin: 'wǒ yě hěn hǎo', english: "I'm also very well", indonesian: 'saya juga sangat baik' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '早上', pinyin: 'zǎoshang', english: 'morning', indonesian: 'pagi' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '早上好', pinyin: 'zǎoshang hǎo', english: 'good morning', indonesian: 'selamat pagi' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '中午', pinyin: 'zhōngwǔ', english: 'noon', indonesian: 'siang' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '中午好', pinyin: 'zhōngwǔ hǎo', english: 'good noon', indonesian: 'selamat siang' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '下午', pinyin: 'xiàwǔ', english: 'afternoon', indonesian: 'sore' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '下午好', pinyin: 'xiàwǔ hǎo', english: 'good afternoon', indonesian: 'selamat sore' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '晚上', pinyin: 'wǎnshang', english: 'evening; night', indonesian: 'malam' },
  { lesson: 'Lesson 2 – Greetings', hanzi: '晚上好', pinyin: 'wǎnshang hǎo', english: 'good evening', indonesian: 'selamat malam' },

  // ── Lesson 4 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 4 – Nationality', hanzi: '哪', pinyin: 'nǎ', english: 'which; where', indonesian: 'mana' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '国', pinyin: 'guó', english: 'country', indonesian: 'negara' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '国家', pinyin: 'guójiā', english: 'country; nation', indonesian: 'negara' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '人', pinyin: 'rén', english: 'person; people', indonesian: 'orang' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '中国', pinyin: 'Zhōngguó', english: 'China', indonesian: 'Tiongkok / China' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '美国', pinyin: 'Měiguó', english: 'America (USA)', indonesian: 'Amerika' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '法国', pinyin: 'Fǎguó', english: 'France', indonesian: 'Prancis' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '日本', pinyin: 'Rìběn', english: 'Japan', indonesian: 'Jepang' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '印度尼西亚', pinyin: 'Yìndùníxīyà', english: 'Indonesia', indonesian: 'Indonesia' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '印尼', pinyin: 'Yìnní', english: 'Indonesia (short)', indonesian: 'Indonesia (singkat)' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '中文', pinyin: 'Zhōngwén', english: 'Chinese (language)', indonesian: 'Bahasa Mandarin' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '这', pinyin: 'zhè', english: 'this', indonesian: 'ini' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '谁', pinyin: 'shéi', english: 'who', indonesian: 'siapa' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '女', pinyin: 'nǚ', english: 'female; woman', indonesian: 'perempuan' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '男', pinyin: 'nán', english: 'male; man', indonesian: 'laki-laki' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '朋友', pinyin: 'péngyou', english: 'friend', indonesian: 'teman' },
  { lesson: 'Lesson 4 – Nationality', hanzi: '泰国', pinyin: 'Tàiguó', english: 'Thailand', indonesian: 'Thailand' },

  // ── Lesson 5 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 5 – Occupation', hanzi: '吗', pinyin: 'ma', english: 'question particle', indonesian: 'partikel tanya' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '医生', pinyin: 'yīshēng', english: 'doctor', indonesian: 'dokter' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '学生', pinyin: 'xuéshēng', english: 'student', indonesian: 'murid' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '做', pinyin: 'zuò', english: 'do; work as', indonesian: 'melakukan; mengerjakan' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '什么', pinyin: 'shénme', english: 'what', indonesian: 'apa' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '工作', pinyin: 'gōngzuò', english: 'job; work', indonesian: 'pekerjaan' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '喂', pinyin: 'wèi', english: 'hello (on the phone)', indonesian: 'halo (saat telepon)' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '还', pinyin: 'hái', english: 'still', indonesian: 'masih' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '忙', pinyin: 'máng', english: 'busy', indonesian: 'sibuk' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '对', pinyin: 'duì', english: 'right; correct', indonesian: 'benar' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '太', pinyin: 'tài', english: 'too; excessively', indonesian: 'terlalu' },
  { lesson: 'Lesson 5 – Occupation', hanzi: '想', pinyin: 'xiǎng', english: 'miss; want', indonesian: 'rindu; ingin' },

  // ── Lesson 6.1 ────────────────────────────────────────────────────
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '零', pinyin: 'líng', english: 'zero', indonesian: 'nol' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '一', pinyin: 'yī', english: 'one', indonesian: 'satu' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '二', pinyin: 'èr', english: 'two', indonesian: 'dua' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '三', pinyin: 'sān', english: 'three', indonesian: 'tiga' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '四', pinyin: 'sì', english: 'four', indonesian: 'empat' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '五', pinyin: 'wǔ', english: 'five', indonesian: 'lima' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '六', pinyin: 'liù', english: 'six', indonesian: 'enam' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '七', pinyin: 'qī', english: 'seven', indonesian: 'tujuh' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '八', pinyin: 'bā', english: 'eight', indonesian: 'delapan' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '九', pinyin: 'jiǔ', english: 'nine', indonesian: 'sembilan' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '十', pinyin: 'shí', english: 'ten', indonesian: 'sepuluh' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '百', pinyin: 'bǎi', english: 'hundred', indonesian: 'ratus' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '千', pinyin: 'qiān', english: 'thousand', indonesian: 'ribu' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '万', pinyin: 'wàn', english: 'ten thousand', indonesian: 'sepuluh ribu' },
  { lesson: 'Lesson 6.1 – Numbers', hanzi: '两', pinyin: 'liǎng', english: 'two (for measure words)', indonesian: 'dua (untuk kata bilangan)' },

  // ── Lesson 6.2 ────────────────────────────────────────────────────
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '爸爸', pinyin: 'bàba', english: 'father; dad', indonesian: 'ayah; papa' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '妈妈', pinyin: 'māma', english: 'mother; mom', indonesian: 'ibu; mama' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '哥哥', pinyin: 'gēge', english: 'older brother', indonesian: 'kakak laki-laki' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '姐姐', pinyin: 'jiějie', english: 'older sister', indonesian: 'kakak perempuan' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '弟弟', pinyin: 'dìdi', english: 'younger brother', indonesian: 'adik laki-laki' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '妹妹', pinyin: 'mèimei', english: 'younger sister', indonesian: 'adik perempuan' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '家', pinyin: 'jiā', english: 'house; home; family', indonesian: 'rumah; keluarga' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '有', pinyin: 'yǒu', english: 'have; has', indonesian: 'ada; punya' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '没有', pinyin: 'méiyǒu', english: 'not have', indonesian: 'tidak ada; tidak punya' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '几', pinyin: 'jǐ', english: 'how many', indonesian: 'berapa' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '口', pinyin: 'kǒu', english: 'measure word for family; mouth', indonesian: 'kata bilangan keluarga; mulut' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '和', pinyin: 'hé', english: 'and', indonesian: 'dan' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '多少', pinyin: 'duōshǎo', english: 'how many; how much', indonesian: 'berapa' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '个', pinyin: 'gè', english: 'general measure word', indonesian: 'kata bilangan umum' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '儿子', pinyin: 'érzi', english: 'son', indonesian: 'anak laki-laki' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '孩子', pinyin: 'háizi', english: 'child; children', indonesian: 'anak' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '女儿', pinyin: "nǚ'ér", english: 'daughter', indonesian: 'anak perempuan' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '今年', pinyin: 'jīnnián', english: 'this year', indonesian: 'tahun ini' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '岁', pinyin: 'suì', english: 'year (of age)', indonesian: 'umur' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '多', pinyin: 'duō', english: 'much; many', indonesian: 'banyak' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '大', pinyin: 'dà', english: 'big; large', indonesian: 'besar' },
  { lesson: 'Lesson 6.2 – Family & Age', hanzi: '多大', pinyin: 'duō dà', english: 'how old; how big', indonesian: 'berapa besar (umur/ukuran)' },

  // ── Lesson 7 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '今天', pinyin: 'jīntiān', english: 'today', indonesian: 'hari ini' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '年', pinyin: 'nián', english: 'year', indonesian: 'tahun' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '月', pinyin: 'yuè', english: 'month; moon', indonesian: 'bulan' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '号', pinyin: 'hào', english: 'date; number', indonesian: 'tanggal; angka' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '日', pinyin: 'rì', english: 'date; sun', indonesian: 'tanggal; matahari' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '星期', pinyin: 'xīngqī', english: 'week', indonesian: 'minggu' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '休息', pinyin: 'xiūxi', english: 'rest', indonesian: 'istirahat' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '会', pinyin: 'huì', english: 'can; be able to', indonesian: 'bisa; dapat' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '做', pinyin: 'zuò', english: 'make; produce', indonesian: 'membuat' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '做饭', pinyin: 'zuòfàn', english: 'cook', indonesian: 'memasak' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '米饭', pinyin: 'mǐfàn', english: 'rice', indonesian: 'nasi' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '面条儿', pinyin: 'miàntiáor', english: 'noodles', indonesian: 'mie' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '饺子', pinyin: 'jiǎozi', english: 'dumplings', indonesian: 'pangsit' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '一些', pinyin: 'yìxiē', english: 'some', indonesian: 'beberapa' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '菜', pinyin: 'cài', english: 'dish; course', indonesian: 'sayur; masakan' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '上班', pinyin: 'shàngbān', english: 'go to work', indonesian: 'masuk kerja' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '下班', pinyin: 'xiàbān', english: 'get off work', indonesian: 'pulang kerja' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '新', pinyin: 'xīn', english: 'new', indonesian: 'baru' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '电脑', pinyin: 'diànnǎo', english: 'computer', indonesian: 'komputer' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '真', pinyin: 'zhēn', english: 'really; truly', indonesian: 'sangat; sungguh' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '好看', pinyin: 'hǎokàn', english: 'good-looking; nice', indonesian: 'bagus' },
  { lesson: 'Lesson 7 – Dates & Likings', hanzi: '喜欢', pinyin: 'xǐhuan', english: 'like', indonesian: 'suka' },

  // ── Lesson 8 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 8 – Phone Number', hanzi: '手机', pinyin: 'shǒujī', english: 'mobile phone', indonesian: 'HP; telepon genggam' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '电话', pinyin: 'diànhuà', english: 'telephone', indonesian: 'telepon' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '号码', pinyin: 'hàomǎ', english: 'number', indonesian: 'nomor' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '多少', pinyin: 'duōshǎo', english: 'how many; how much', indonesian: 'berapa' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '明天', pinyin: 'míngtiān', english: 'tomorrow', indonesian: 'besok' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '去', pinyin: 'qù', english: 'go to', indonesian: 'pergi' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '哪儿', pinyin: 'nǎr', english: 'where', indonesian: 'mana' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '想', pinyin: 'xiǎng', english: 'want; would like', indonesian: 'ingin; mau' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '超市', pinyin: 'chāoshì', english: 'supermarket', indonesian: 'supermarket' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '买', pinyin: 'mǎi', english: 'buy', indonesian: 'membeli' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '东西', pinyin: 'dōngxi', english: 'thing', indonesian: 'barang' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '些', pinyin: 'xiē', english: 'some; a few', indonesian: 'beberapa' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '牛奶', pinyin: 'niúnǎi', english: "(cow's) milk", indonesian: 'susu (sapi)' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '吃', pinyin: 'chī', english: 'eat', indonesian: 'makan' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '晚饭', pinyin: 'wǎnfàn', english: 'dinner', indonesian: 'makan malam' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '那边', pinyin: 'nàbiān', english: 'there', indonesian: 'di sisi itu' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '这', pinyin: 'zhè', english: 'this', indonesian: 'ini' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '包子', pinyin: 'bāozi', english: 'steamed bun', indonesian: 'bakpao' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '非常', pinyin: 'fēicháng', english: 'very; extremely', indonesian: 'sangat' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '好吃', pinyin: 'hǎochī', english: 'delicious', indonesian: 'enak' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '怎么', pinyin: 'zěnme', english: 'how', indonesian: 'bagaimana cara' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '坐', pinyin: 'zuò', english: 'sit; take (transport)', indonesian: 'duduk; naik' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '出租车', pinyin: 'chūzūchē', english: 'taxi', indonesian: 'taksi' },
  { lesson: 'Lesson 8 – Phone Number', hanzi: '西安饭店', pinyin: "Xī'ān fàndiàn", english: "Xi'an Restaurant", indonesian: 'Restoran Xi\'an' },

  // ── Lesson 9 ──────────────────────────────────────────────────────
  { lesson: 'Lesson 9 – Time', hanzi: '现在', pinyin: 'xiànzài', english: 'now', indonesian: 'sekarang' },
  { lesson: 'Lesson 9 – Time', hanzi: '点', pinyin: 'diǎn', english: "o'clock", indonesian: 'jam' },
  { lesson: 'Lesson 9 – Time', hanzi: '分', pinyin: 'fēn', english: 'minute', indonesian: 'menit' },
  { lesson: 'Lesson 9 – Time', hanzi: '课', pinyin: 'kè', english: 'class; lesson', indonesian: 'kelas; pelajaran' },
  { lesson: 'Lesson 9 – Time', hanzi: '见', pinyin: 'jiàn', english: 'meet', indonesian: 'bertemu' },
  { lesson: 'Lesson 9 – Time', hanzi: '吧', pinyin: 'ba', english: 'suggestion particle', indonesian: 'partikel penegas' },
  { lesson: 'Lesson 9 – Time', hanzi: '上午', pinyin: 'shàngwǔ', english: 'morning (9am–noon)', indonesian: 'pagi hari' },
  { lesson: 'Lesson 9 – Time', hanzi: '傍晚', pinyin: 'bàngwǎn', english: 'dusk; early evening', indonesian: 'sore hari' },
  { lesson: 'Lesson 9 – Time', hanzi: '夜里', pinyin: 'yèlǐ', english: 'late night', indonesian: 'malam hari (larut)' },
  { lesson: 'Lesson 9 – Time', hanzi: '凌晨', pinyin: 'língchén', english: 'early dawn', indonesian: 'subuh' },
  { lesson: 'Lesson 9 – Time', hanzi: '电影院', pinyin: 'diànyǐngyuàn', english: 'cinema', indonesian: 'bioskop' },
  { lesson: 'Lesson 9 – Time', hanzi: '看', pinyin: 'kàn', english: 'watch; see; read', indonesian: 'nonton; lihat; baca' },
  { lesson: 'Lesson 9 – Time', hanzi: '电影', pinyin: 'diànyǐng', english: 'movie', indonesian: 'film' },
  { lesson: 'Lesson 9 – Time', hanzi: '事', pinyin: 'shì', english: 'thing; affair', indonesian: 'sesuatu; masalah' },
  { lesson: 'Lesson 9 – Time', hanzi: '上课', pinyin: 'shàngkè', english: 'attend a class', indonesian: 'masuk kelas' },
  { lesson: 'Lesson 9 – Time', hanzi: '下课', pinyin: 'xiàkè', english: 'dismiss a class', indonesian: 'selesai kelas' },
  { lesson: 'Lesson 9 – Time', hanzi: '半', pinyin: 'bàn', english: 'half', indonesian: 'setengah' },
  { lesson: 'Lesson 9 – Time', hanzi: '刻', pinyin: 'kè', english: 'quarter (15 minutes)', indonesian: 'seperempat (15 menit)' },
  { lesson: 'Lesson 9 – Time', hanzi: '在', pinyin: 'zài', english: 'be at; in; on', indonesian: 'di' },
  { lesson: 'Lesson 9 – Time', hanzi: '家', pinyin: 'jiā', english: 'home', indonesian: 'rumah' },
  { lesson: 'Lesson 9 – Time', hanzi: '里', pinyin: 'lǐ', english: 'inside', indonesian: 'dalam' },
  { lesson: 'Lesson 9 – Time', hanzi: '医院', pinyin: 'yīyuàn', english: 'hospital', indonesian: 'rumah sakit' },
  { lesson: 'Lesson 9 – Time', hanzi: '上班', pinyin: 'shàngbān', english: 'go to work', indonesian: 'pergi kerja' },
  { lesson: 'Lesson 9 – Time', hanzi: '下班', pinyin: 'xiàbān', english: 'get off work', indonesian: 'pulang kerja' },
  { lesson: 'Lesson 9 – Time', hanzi: '店', pinyin: 'diàn', english: 'shop; store', indonesian: 'toko' },
  { lesson: 'Lesson 9 – Time', hanzi: '菜', pinyin: 'cài', english: 'vegetable; greens', indonesian: 'sayur' },
  { lesson: 'Lesson 9 – Time', hanzi: '分钟', pinyin: 'fēnzhōng', english: 'minute (duration)', indonesian: 'menit' },
  { lesson: 'Lesson 9 – Time', hanzi: '后', pinyin: 'hòu', english: 'after; later', indonesian: 'setelah; nanti' },

  // ── Lesson 10 ─────────────────────────────────────────────────────
  { lesson: 'Lesson 10 – Location', hanzi: '房间', pinyin: 'fángjiān', english: 'room', indonesian: 'kamar' },
  { lesson: 'Lesson 10 – Location', hanzi: '外', pinyin: 'wài', english: 'outside', indonesian: 'luar' },
  { lesson: 'Lesson 10 – Location', hanzi: '只', pinyin: 'zhī', english: 'measure word for animals', indonesian: 'kata satuan binatang' },
  { lesson: 'Lesson 10 – Location', hanzi: '小', pinyin: 'xiǎo', english: 'small; little', indonesian: 'kecil' },
  { lesson: 'Lesson 10 – Location', hanzi: '猫', pinyin: 'māo', english: 'cat', indonesian: 'kucing' },
  { lesson: 'Lesson 10 – Location', hanzi: '没', pinyin: 'méi', english: 'no; not; not yet', indonesian: 'tidak; belum' },
  { lesson: 'Lesson 10 – Location', hanzi: '看见', pinyin: 'kànjiàn', english: 'see; catch sight of', indonesian: 'melihat; terlihat' },
  { lesson: 'Lesson 10 – Location', hanzi: '桌子', pinyin: 'zhuōzi', english: 'table; desk', indonesian: 'meja' },
  { lesson: 'Lesson 10 – Location', hanzi: '下', pinyin: 'xià', english: 'below; under (position)', indonesian: 'bawah' },
  { lesson: 'Lesson 10 – Location', hanzi: '漂亮', pinyin: 'piàoliang', english: 'pretty; beautiful', indonesian: 'cantik' },
  { lesson: 'Lesson 10 – Location', hanzi: '边', pinyin: 'biān', english: 'side; edge; direction', indonesian: 'sebelah' },
  { lesson: 'Lesson 10 – Location', hanzi: '左边', pinyin: 'zuǒbiān', english: 'left side', indonesian: 'sebelah kiri' },
  { lesson: 'Lesson 10 – Location', hanzi: '右边', pinyin: 'yòubiān', english: 'right side', indonesian: 'sebelah kanan' },
  { lesson: 'Lesson 10 – Location', hanzi: '前边', pinyin: 'qiánbiān', english: 'front side', indonesian: 'depan' },
  { lesson: 'Lesson 10 – Location', hanzi: '后边', pinyin: 'hòubiān', english: 'back side', indonesian: 'belakang' },
  { lesson: 'Lesson 10 – Location', hanzi: '面', pinyin: 'miàn', english: 'surface; face; side', indonesian: 'sisi' },
  { lesson: 'Lesson 10 – Location', hanzi: '下面', pinyin: 'xiàmiàn', english: 'below; under', indonesian: 'bawah' },
  { lesson: 'Lesson 10 – Location', hanzi: '上面', pinyin: 'shàngmiàn', english: 'above; top', indonesian: 'atas' },
  { lesson: 'Lesson 10 – Location', hanzi: '里面', pinyin: 'lǐmiàn', english: 'inside', indonesian: 'dalam' },
  { lesson: 'Lesson 10 – Location', hanzi: '外面', pinyin: 'wàimiàn', english: 'outside', indonesian: 'luar' },
  { lesson: 'Lesson 10 – Location', hanzi: '在', pinyin: 'zài', english: 'at; in', indonesian: 'di' },
  { lesson: 'Lesson 10 – Location', hanzi: '学校', pinyin: 'xuéxiào', english: 'school', indonesian: 'sekolah' },
  { lesson: 'Lesson 10 – Location', hanzi: '书店', pinyin: 'shūdiàn', english: 'bookstore', indonesian: 'toko buku' },
  { lesson: 'Lesson 10 – Location', hanzi: '能', pinyin: 'néng', english: 'can; be able to', indonesian: 'bisa; dapat' },
  { lesson: 'Lesson 10 – Location', hanzi: '到', pinyin: 'dào', english: 'arrive; reach', indonesian: 'sampai' },
  { lesson: 'Lesson 10 – Location', hanzi: '午饭', pinyin: 'wǔfàn', english: 'lunch', indonesian: 'makan siang' },
  { lesson: 'Lesson 10 – Location', hanzi: '饭', pinyin: 'fàn', english: 'meal', indonesian: 'makanan' },
  { lesson: 'Lesson 10 – Location', hanzi: '大', pinyin: 'dà', english: 'big; large', indonesian: 'besar' },
  { lesson: 'Lesson 10 – Location', hanzi: '病人', pinyin: 'bìngrén', english: 'patient', indonesian: 'orang sakit; pasien' },
  { lesson: 'Lesson 10 – Location', hanzi: '老', pinyin: 'lǎo', english: 'old', indonesian: 'tua' },

  // ── Lesson 11 ─────────────────────────────────────────────────────
  { lesson: 'Lesson 11 – Review', hanzi: '那个', pinyin: 'nàge', english: 'that (one)', indonesian: 'yang itu' },
  { lesson: 'Lesson 11 – Review', hanzi: '椅子', pinyin: 'yǐzi', english: 'chair', indonesian: 'kursi' },
  { lesson: 'Lesson 11 – Review', hanzi: '上', pinyin: 'shàng', english: 'above; on', indonesian: 'atas' },
  { lesson: 'Lesson 11 – Review', hanzi: '本', pinyin: 'běn', english: 'measure word for books', indonesian: 'kata bilangan buku' },
  { lesson: 'Lesson 11 – Review', hanzi: '书', pinyin: 'shū', english: 'book', indonesian: 'buku' },
  { lesson: 'Lesson 11 – Review', hanzi: '第', pinyin: 'dì', english: 'ordinal number marker', indonesian: 'penanda urutan (ke-)' },
  { lesson: 'Lesson 11 – Review', hanzi: '学习', pinyin: 'xuéxí', english: 'study', indonesian: 'belajar' },
  { lesson: 'Lesson 11 – Review', hanzi: '做', pinyin: 'zuò', english: 'do', indonesian: 'melakukan' },
  { lesson: 'Lesson 11 – Review', hanzi: '白天', pinyin: 'báitiān', english: 'daytime', indonesian: 'siang hari' },
  { lesson: 'Lesson 11 – Review', hanzi: '读书', pinyin: 'dúshū', english: 'read a book', indonesian: 'membaca buku' },
  { lesson: 'Lesson 11 – Review', hanzi: '和', pinyin: 'hé', english: 'and; with', indonesian: 'dan; dengan' },
  { lesson: 'Lesson 11 – Review', hanzi: '朋友', pinyin: 'péngyou', english: 'friend', indonesian: 'teman' },
  { lesson: 'Lesson 11 – Review', hanzi: '唱', pinyin: 'chàng', english: 'sing', indonesian: 'menyanyi' },
  { lesson: 'Lesson 11 – Review', hanzi: '歌', pinyin: 'gē', english: 'song', indonesian: 'lagu' },
  { lesson: 'Lesson 11 – Review', hanzi: '好听', pinyin: 'hǎotīng', english: 'pleasant to hear', indonesian: 'enak didengar' },
  { lesson: 'Lesson 11 – Review', hanzi: '电视', pinyin: 'diànshì', english: 'TV', indonesian: 'televisi' },
  { lesson: 'Lesson 11 – Review', hanzi: '狗', pinyin: 'gǒu', english: 'dog', indonesian: 'anjing' },
  { lesson: 'Lesson 11 – Review', hanzi: '玩', pinyin: 'wán', english: 'play', indonesian: 'bermain' },

  // ── Lesson 12 ─────────────────────────────────────────────────────
  { lesson: 'Lesson 12 – Price', hanzi: '杯子', pinyin: 'bēizi', english: 'cup', indonesian: 'gelas' },
  { lesson: 'Lesson 12 – Price', hanzi: '售货员', pinyin: 'shòuhuòyuán', english: 'shop assistant', indonesian: 'pelayan toko' },
  { lesson: 'Lesson 12 – Price', hanzi: '这边', pinyin: 'zhèbiān', english: 'here; this side', indonesian: 'di sini' },
  { lesson: 'Lesson 12 – Price', hanzi: '钱', pinyin: 'qián', english: 'money', indonesian: 'uang' },
  { lesson: 'Lesson 12 – Price', hanzi: '这些', pinyin: 'zhèxiē', english: 'these', indonesian: 'beberapa ini' },
  { lesson: 'Lesson 12 – Price', hanzi: '块', pinyin: 'kuài', english: 'yuan (colloquial)', indonesian: 'yuan (sehari-hari)' },
  { lesson: 'Lesson 12 – Price', hanzi: '那些', pinyin: 'nàxiē', english: 'those', indonesian: 'beberapa itu' },
  { lesson: 'Lesson 12 – Price', hanzi: '元', pinyin: 'yuán', english: 'yuan (formal)', indonesian: 'yuan (formal)' },
  { lesson: 'Lesson 12 – Price', hanzi: '角', pinyin: 'jiǎo', english: '1/10 yuan (formal)', indonesian: 'sepersepuluh yuan (formal)' },
  { lesson: 'Lesson 12 – Price', hanzi: '分', pinyin: 'fēn', english: 'cent; 1/100 yuan', indonesian: 'sen; seperseratus yuan' },
  { lesson: 'Lesson 12 – Price', hanzi: '毛', pinyin: 'máo', english: '1/10 yuan (colloquial)', indonesian: 'sepersepuluh yuan (sehari-hari)' },
  { lesson: 'Lesson 12 – Price', hanzi: '水果', pinyin: 'shuǐguǒ', english: 'fruit', indonesian: 'buah' },
  { lesson: 'Lesson 12 – Price', hanzi: '少', pinyin: 'shǎo', english: 'few; little', indonesian: 'sedikit' },
  { lesson: 'Lesson 12 – Price', hanzi: '斤', pinyin: 'jīn', english: 'unit of weight (0.5 kg)', indonesian: 'satuan berat (0,5 kg)' },
  { lesson: 'Lesson 12 – Price', hanzi: '苹果', pinyin: 'píngguǒ', english: 'apple', indonesian: 'apel' },
  { lesson: 'Lesson 12 – Price', hanzi: '便宜', pinyin: 'piányi', english: 'cheap; affordable', indonesian: 'murah' },
  { lesson: 'Lesson 12 – Price', hanzi: '商店', pinyin: 'shāngdiàn', english: 'store; shop', indonesian: 'toko' },
  { lesson: 'Lesson 12 – Price', hanzi: '衣服', pinyin: 'yīfu', english: 'clothes', indonesian: 'baju; pakaian' },
  { lesson: 'Lesson 12 – Price', hanzi: '件', pinyin: 'jiàn', english: 'measure word for clothing', indonesian: 'kata satuan baju' },
  { lesson: 'Lesson 12 – Price', hanzi: '怎么样', pinyin: 'zěnmeyàng', english: 'how about; what about', indonesian: 'bagaimana' },
  { lesson: 'Lesson 12 – Price', hanzi: '贵', pinyin: 'guì', english: 'expensive', indonesian: 'mahal' },
  { lesson: 'Lesson 12 – Price', hanzi: '穿', pinyin: 'chuān', english: 'wear; put on', indonesian: 'memakai' },
  { lesson: 'Lesson 12 – Price', hanzi: '那儿', pinyin: 'nàr', english: 'there', indonesian: 'di sana' },

  // ── Lesson 13 ─────────────────────────────────────────────────────
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '时候', pinyin: 'shíhou', english: '(a point in) time', indonesian: 'waktu' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '知道', pinyin: 'zhīdào', english: 'know; realize', indonesian: 'tahu' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '正在', pinyin: 'zhèngzài', english: 'in the process of (progressive)', indonesian: 'sedang' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '在', pinyin: 'zài', english: 'in the process of (V-ing)', indonesian: 'sedang' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '找', pinyin: 'zhǎo', english: 'look for', indonesian: 'mencari' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '开车', pinyin: 'kāichē', english: 'drive (a vehicle)', indonesian: 'menyetir' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '车', pinyin: 'chē', english: 'vehicle', indonesian: 'kendaraan' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '读', pinyin: 'dú', english: 'attend school; study; read', indonesian: 'belajar; membaca' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '大学', pinyin: 'dàxué', english: 'university; college', indonesian: 'universitas' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '大学生', pinyin: 'dàxuéshēng', english: 'college student', indonesian: 'mahasiswa' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '学', pinyin: 'xué', english: 'study; learn', indonesian: 'belajar' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '医', pinyin: 'yī', english: 'medicine (field of study)', indonesian: '(ilmu) medis' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '起床', pinyin: 'qǐchuáng', english: 'get up', indonesian: 'bangun' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '睡觉', pinyin: 'shuìjiào', english: 'sleep', indonesian: 'tidur' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '睡', pinyin: 'shuì', english: 'sleep', indonesian: 'tidur' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '那里', pinyin: 'nàlǐ', english: 'there; that place', indonesian: 'sana' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '哪里', pinyin: 'nǎlǐ', english: 'where', indonesian: 'mana' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '昨天', pinyin: 'zuótiān', english: 'yesterday', indonesian: 'kemarin' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '问', pinyin: 'wèn', english: 'ask', indonesian: 'bertanya' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '对', pinyin: 'duì', english: 'to; towards', indonesian: 'terhadap' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '说', pinyin: 'shuō', english: 'speak; talk; say', indonesian: 'berbicara' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '要', pinyin: 'yào', english: 'want; wish', indonesian: 'mau; ingin' },
  { lesson: 'Lesson 13 – 在 as V-ing', hanzi: '小朋友', pinyin: 'xiǎopéngyǒu', english: 'child; kid', indonesian: 'anak kecil' },
]

async function seed() {
  console.log('Step 1: Upserting lessons...')
  const { error: lessonErr } = await supabase
    .from('lessons')
    .upsert(lessonNames.map(name => ({ name })), { onConflict: 'name' })
  if (lessonErr) { console.error('Lesson error:', lessonErr.message); process.exit(1) }

  const { data: allLessons, error: fetchErr } = await supabase.from('lessons').select('*')
  if (fetchErr) { console.error('Fetch error:', fetchErr.message); process.exit(1) }

  const lessonMap = {}
  allLessons.forEach(l => { lessonMap[l.name] = l.id })
  console.log(`  Lessons ready: ${allLessons.length}`)

  console.log(`Step 2: Inserting ${vocabulary.length} characters...`)
  const rows = vocabulary.map(v => ({
    hanzi: v.hanzi,
    pinyin: v.pinyin,
    english: v.english,
    indonesian: v.indonesian,
    lesson_id: lessonMap[v.lesson],
  }))

  const { error: charErr } = await supabase
    .from('characters')
    .upsert(rows, { onConflict: 'hanzi,lesson_id' })

  if (charErr) {
    console.error('Character error:', charErr.message)
    process.exit(1)
  }

  console.log('Done! All lessons and characters seeded successfully.')
}

seed()
